services:
  webserver:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      APP_URL: https://${SERVER_NAME:-localhost}
      SERVER_NAME: ${SERVER_NAME:-localhost}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${DB_USERNAME:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME:-app} -d ${DB_DATABASE:-app}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  caddy_data:
  caddy_config:
  database_data:
